# Data header
# Altitude (z),Temperature (K),Scale Height,Pressure,Density

dataPath = "C:/Users/Ramon/Documents/Uni/Hidrodinamica y Magnetohidrodinamica\
/EquilibrioHidrostatico/out/build/x64-debug/results/results.csv"

data = dlmread(dataPath, ',', 1, 0)
altitude = data(:, 1)
temperature = data(:, 2)
scale_height = data(:, 3)
pressure = data(:, 4)
density = data(:, 5)

subplot(4, 1, 1)
plot_data_helper(altitude, temperature, ...
          {"Altitude (z)", "m"}, {"Temperature", "K"}, ...
          "Temperature as function of altitude", ...
          "-or", true)
                    
subplot(4, 1, 2)          
plot_data_helper(altitude, scale_height, ...
          {"Altitude (z)", "m"}, {"Scale Height", "m"}, ...
          "Scale height as function of altitude", ...
          "-oc", true)
          
subplot(4, 1, 3)
plot_data_helper(altitude, pressure, ...
          {"Altitude (z)", "m"}, {"Pressure", "kg * m^{-1} * s^{-2}"}, ...
          "Pressure as function of altitude", ...
          "-ob", true)
          
subplot(4, 1, 4)
plot_data_helper(altitude, density, ...
          {"Altitude (z)", "m"}, {"Density", "kg * m^{-3}"}, ...
          "Density as function of altitude", ...
          "-og", true) 